const {v4:uuid} = require('uuid');

const doctors = [
    {
        id: uuid(),
        username: 'sameerlohia',
        password: 'pw1',
        name: "Dr. Sameer Lohia",
        degrees : ["MBBS", "MS", "DNB"],
        position: "Senior Consultant Nephrology",
        hospital: "Apollo Hospitals",
        speciality: ["Nephrology", "Urologist"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Sameer Lohia is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "sameerlohia@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/male-doc.png'
    },
    {
        id: uuid(),
        username: 'satishkhanna',
        password: 'pw2',
        name: "Dr. Satish Khanna",
        degrees : ["MBBS", "MS"],
        position: "Senior Consultant Dermatologist",
        hospital: "Quantum Hospitals",
        speciality: ["Dermatology"],
        exp: "14 years of experience and 2 years training in London",
        languages: ["English","Hindi","Bengali","Assamese"],
        contact: "+91 9876374810",
        about: "Dr. Satish Khanna is a board-certified Hermatologist at the Quantum Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "satishkhanna@gmail.com",
        registration: "AS-8354-52332",
        image: '/img/male-doc.png'
    },
    {
        id: uuid(),
        username: 'meenakshi',
        password: 'pw3',
        name: "Dr. K. Meenakshi",
        degrees : ["MBBS", "MS", "BDS"],
        position: "Head Dermatologist",
        hospital: "Bioclinic Hospitals",
        speciality: ["Dermatology", "Pediatrician"],
        exp: "10 years+",
        languages: ["English","Hindi"],
        contact: "+91 9876478210",
        about: "Dr. K. Meenakshi is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "kmeenakshi@gmail.com",
        registration: "AS-8312-19432",
        image: '/img/female-doc.png'
    },
    {
        id: uuid(),
        username: 'rupakgaur',
        password: 'pw4',
        name: "Dr. Rupak Gaur",
        degrees : ["MBBS", "MS", "BPT"],
        position: "Senior Consultant Gynecologist",
        hospital: "Apollo Hospitals",
        speciality: ["Sexology", "Gynecology"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Rupak Gaur is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "rupakgaur@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/male-doc.png'
    },
    {
        id: uuid(),
        username: 'hanuradha',
        password: 'pw5',
        name: "Dr. H. Anuradha",
        degrees : ["MBBS", "BAMS", "DNB"],
        position: "Head Gastroenterologist",
        hospital: "Apollo Hospitals",
        speciality: ["Neurology", "Gastroenterology"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Sameer Lohia is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "sameerlohia@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/female-doc.png'
    },
    {
        id: uuid(),
        username: 'anjanbarkataky',
        password: 'pw6',
        name: "Dr. Anjan Barkataky",
        degrees : ["MBBS", "MS", "DM"],
        position: "Senior Consultant Nephrology",
        hospital: "Apollo Hospitals",
        speciality: ["Dermatology","Otology", "Sexology"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Sameer Lohia is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "sameerlohia@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/female-doc.png'
    },
    {
        id: uuid(),
        username: 'chandrasekhar',
        password: 'pw7',
        name: "Dr. Chandrasekhar",
        degrees : ["MBBS", "MS", "DNB"],
        position: "Senior Consultant Nephrology",
        hospital: "Apollo Hospitals",
        speciality: ["Gastroenterology", "Pediatrician"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Sameer Lohia is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "sameerlohia@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/male-doc.png'
    },
    {
        id: uuid(),
        username: 'sunilprakash',
        password: 'pw8',
        name: "Dr. Sunil Prakash",
        degrees : ["MBBS", "MS", "DNB"],
        position: "Senior Consultant Nephrology",
        hospital: "Apollo Hospitals",
        speciality: ["Neurology", "Gynecology", "Otology"],
        exp: "20 years+",
        languages: ["English","Hindi","Bengali","Telegu"],
        contact: "+91 9876543210",
        about: "Dr. Sameer Lohia is a board-certified Nephrology at the Apollo Hospitals,Chennai for the past 7 years. He has completed his medical training at Louisiana State University School of Medicine in New Orleans. Patients from all around the state and entire country come to Dr. Sameer Lohia with lots of hope and the doctor ensures that the patients are satisfied with the treatments, with his experience and the techniques he uses as a Nephrology.",
        email: "sameerlohia@gmail.com",
        registration: "AS-8374-09432",
        image: '/img/male-doc.png'
    },
]

module.exports = doctors;